(define (domain HARBOR_V01)
  (:requirements :strips :typing)
  (:types block stack crane bottom)
  (:predicates (hold ?c - crane ?x - block)
  	       (empty_crane ?c - crane)
	       (empty_tape)
	       (block_in_tape ?x - block)
	       (available ?x - block)
	       (on ?x - block ?y - (either block bottom) )
	       (top ?x - (either block bottom))
	       (at ?x - (either block bottom) ?s - stack)
	       (handle ?c - crane ?s - stack)
	       
  )
  (:action pick-from-stack
    :parameters (?x - block ?y - (either block bottom) ?s - stack ?c - crane)
    :precondition (and (empty_crane ?c)
                       (handle ?c ?s)
		       (at ?x ?s)
		       (top ?x)
		       (on ?x ?y))
    :effect (and (not (empty_crane ?c))
                 (hold ?c ?x)
		 (not (on ?x ?y))
		 (not (at ?x ?s))
		 (not (top ?x))
		 (top ?y)
            )
  )
  (:action put-on-stack
    :parameters (?x - block ?y - (either block bottom) ?s - stack ?c - crane)
    :precondition (and (hold ?c ?x)
                       (handle ?c ?s)
    		       (top ?y)
		       (at ?y ?s)
    		  )
    :effect (and (empty_crane ?c)
                 (not (hold ?c ?x))
		 (on ?x ?y)
		 (at ?x ?s)
		 (top ?x)
		 (not (top ?y))
            )
  )
  (:action pick-from-tape
    :parameters (?x - block ?c - crane)
    :precondition (and (block_in_tape ?x)
                       (empty_crane ?c))
		       
    :effect (and (not (block_in_tape ?x)) (not (empty_crane ?c))
                 (empty_tape) (hold ?c ?x))
  )
  (:action put-on-tape
    :parameters (?x - block ?c - crane)
    :precondition (and (empty_tape)
                       (hold ?c ?x))
		       
    :effect (and (block_in_tape ?x) (empty_crane ?c)
                 (not (empty_tape)) (not (hold ?c ?x)))
  )
)
