(define (domain HARBOR_V03)
  (:requirements :strips :typing)
  (:types block o_block stack crane bottom dock height)
  (:predicates (hold ?c - crane ?x - (either block o_block))
  	       (empty_crane ?c - crane)
	       (empty_tape)
	       (block_in_tape ?x - (either block o_block))
	       (available ?x - o_block)
	       (on ?x - (either o_block block) ?y - (either o_block block bottom) )
	       (top ?x - (either block bottom o_block))
	       (at ?x - (either block bottom o_block) ?s - stack)
	       (at_dock ?x - (either block o_block bottom) ?d - dock)
	       (handle ?c - crane ?s - stack)
	       (max_height ?h - height)
	       (height ?s - stack ?h - height)
	       (next_h ?a ?b - height)
	       (prev_h ?a ?b - height)
  )
  (:action pick-from-stack-bb
    :parameters (?x - block ?y - (either block bottom) ?s - stack ?c - crane ?d - dock ?ch - height ?nh - height)
    :precondition (and (empty_crane ?c)
                       (handle ?c ?s)
		       (at ?x ?s)
		       (top ?x)
		       (on ?x ?y)
		       (at_dock ?x ?d)
		       (height ?s ?ch)
		       (prev_h ?nh ?ch))
    :effect (and (not (empty_crane ?c))
                 (hold ?c ?x)
		 (not (on ?x ?y))
		 (not (at ?x ?s))
		 (not (top ?x))
		 (top ?y)
		 (not (at_dock ?x ?d))
		 (not (height ?s ?ch))
		 (height ?s ?nh))
  )

  (:action pick-from-stack-oo
    :parameters (?x - o_block ?y - o_block ?s - stack ?c - crane ?d - dock ?ch - height ?nh - height)
    :precondition (and (empty_crane ?c)
                       (handle ?c ?s)
		       (at ?x ?s)
		       (top ?x)
		       (on ?x ?y)
		       (at_dock ?x ?d)
		       (height ?s ?ch)
		       (prev_h ?nh ?ch))
    :effect (and (not (empty_crane ?c))
                 (hold ?c ?x)
		 (not (on ?x ?y))
		 (not (at ?x ?s))
		 (not (top ?x))
		 (not (available ?x))
		 (top ?y)
		 (not (at_dock ?x ?d))
		 (not (height ?s ?ch))
		 (height ?s ?nh))
  )

  (:action pick-from-stack-ob
    :parameters (?x - o_block ?y - (either block bottom) ?s - stack ?c - crane ?d - dock ?ch - height ?nh - height)
    :precondition (and (empty_crane ?c)
                       (handle ?c ?s)
		       (at ?x ?s)
		       (top ?x)
		       (on ?x ?y)
		       (at_dock ?x ?d)
		       (height ?s ?ch)
		       (prev_h ?nh ?ch))
    :effect (and (not (empty_crane ?c))
                 (hold ?c ?x)
		 (not (on ?x ?y))
		 (not (at ?x ?s))
		 (not (top ?x))
		 (not (available ?x))
		 (top ?y)
		 (not (at_dock ?x ?d))
                 (not (height ?s ?ch))
		 (height ?s ?nh))
  )

  (:action pick-from-stack-bo
    :parameters (?x - block ?y - o_block ?s - stack ?c - crane ?d - dock ?ch - height ?nh - height)
    :precondition (and (empty_crane ?c)
                       (handle ?c ?s)
		       (at ?x ?s)
		       (top ?x)
		       (on ?x ?y)
		       (at_dock ?x ?d)
		       (height ?s ?ch)
		       (prev_h ?nh ?ch))
    :effect (and (not (empty_crane ?c))
                 (hold ?c ?x)
		 (not (on ?x ?y))
		 (not (at ?x ?s))
		 (not (top ?x))
		 (top ?y)
		 (not (at_dock ?x ?d))
		 (available ?y)
                 (not (height ?s ?ch))
		 (height ?s ?nh))
  )


  (:action put-on-stack-bb
    :parameters (?x - block ?y - (either block bottom) ?s - stack ?c - crane ?d - dock ?ch - height ?nh - height ?mh - height)
    :precondition (and (hold ?c ?x)
                       (handle ?c ?s)
    		       (top ?y)
		       (at ?y ?s)
		       (at_dock ?y ?d)
		       (height ?s ?ch)
		       (next_h ?nh ?ch)
		       (max_height ?mh)
		       (not (next_h ?nh ?mh)))
    :effect (and (empty_crane ?c)
                 (not (hold ?c ?x))
		 (on ?x ?y)
		 (at ?x ?s)
		 (top ?x)
		 (not (top ?y))
		 (at_dock ?x ?d)
                 (not (height ?s ?ch))
		 (height ?s ?nh))
  )

  (:action put-on-stack-oo
    :parameters (?x - o_block ?y - o_block ?s - stack ?c - crane ?d - dock ?ch - height ?nh - height ?mh - height)
    :precondition (and (hold ?c ?x)
                       (handle ?c ?s)
    		       (top ?y)
		       (at ?y ?s)
		       (at_dock ?y ?d)
		       (height ?s ?ch)
		       (next_h ?nh ?ch)
		       (max_height ?mh)
		       (not (next_h ?nh ?mh)))
    :effect (and (empty_crane ?c)
                 (not (hold ?c ?x))
		 (on ?x ?y)
		 (at ?x ?s)
		 (top ?x)
		 (not (top ?y))
		 (at_dock ?x ?d)
		 (available ?x)
                 (not (height ?s ?ch))
		 (height ?s ?nh))
  )



  (:action put-on-stack-ob
    :parameters (?x - o_block ?y - (either block bottom) ?s - stack ?c - crane ?d - dock ?ch - height ?nh - height ?mh - height)
    :precondition (and (hold ?c ?x)
                       (handle ?c ?s)
    		       (top ?y)
		       (at ?y ?s)
		       (at_dock ?y ?d)
		       (height ?s ?ch)
		       (next_h ?nh ?ch)
		       (max_height ?mh)
		       (not (next_h ?nh ?mh)))
    :effect (and (empty_crane ?c)
                 (not (hold ?c ?x))
		 (on ?x ?y)
		 (at ?x ?s)
		 (top ?x)
		 (not (top ?y))
		 (at_dock ?x ?d)
		 (available ?x)
                 (not (height ?s ?ch))
		 (height ?s ?nh))
  )


 (:action put-on-stack-bo
    :parameters (?x - block ?y - o_block ?s - stack ?c - crane ?d - dock ?ch - height ?nh - height ?mh - height)
    :precondition (and (hold ?c ?x)
                       (handle ?c ?s)
    		       (top ?y)
		       (at ?y ?s)
		       (at_dock ?y ?d)
		       (height ?s ?ch)
		       (next_h ?nh ?ch)
		       (max_height ?mh)
		       (not (next_h ?nh ?mh)))
    :effect (and (empty_crane ?c)
                 (not (hold ?c ?x))
		 (on ?x ?y)
		 (at ?x ?s)
		 (top ?x)
		 (not (top ?y))
		 (at_dock ?x ?d)
		 (not (available ?y))
                 (not (height ?s ?ch))
		 (height ?s ?nh))
  )


  (:action pick-from-tape
    :parameters (?x - (either block o_block) ?c - crane)
    :precondition (and (block_in_tape ?x)
                       (empty_crane ?c))
		       
    :effect (and (not (block_in_tape ?x)) (not (empty_crane ?c))
                 (empty_tape) (hold ?c ?x))
  )
  (:action put-on-tape
    :parameters (?x - (either block o_block) ?c - crane)
    :precondition (and (empty_tape)
                       (hold ?c ?x))
		       
    :effect (and (block_in_tape ?x) (empty_crane ?c)
                 (not (empty_tape)) (not (hold ?c ?x)))
  )
)
